### ISSUE TITLE
Github Action sample file should use Node v16

### ISSUE THREAD

**Issue by teng-vungle** [looker-open-source/look-at-me-sideways#138]
Hi there—

The sample code on [this page](https://looker-open-source.github.io/look-at-me-sideways/github-action) should be updated to use Node v16.

### Details

I was getting this warning from Github, using Node v10:

> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/setup-node@v1. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

And this error from my Github Action log after I updated LAMS from v2 to v3:

```
/opt/hostedtoolcache/node/12.22.12/x64/lib/node_modules/@looker/look-at-me-sideways/lib/custom-rule/result-interpreter.js:17
			location: formatPath(match?.path)
			                           ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/opt/hostedtoolcache/node/12.22.12/x64/lib/node_modules/@looker/look-at-me-sideways/lib/custom-rule/custom-rule.js:6:27)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at module.exports (/opt/hostedtoolcache/node/12.22.12/x64/lib/node_modules/@looker/look-at-me-sideways/index.js:60:33)
    at /opt/hostedtoolcache/node/12.22.12/x64/lib/node_modules/@looker/look-at-me-sideways/cli.js:28:8
Error reporting is disabled. Run with --reporting=yes to report, or see PRIVACY.md for more info
Error: Process completed with exit code 1.
```

The problem went away right after I updated Github Action to use Node v16 (as opposed to v10 suggested in the sample). Updating the sample code would help a lot of people who are getting started with LAMS.

And thank you for the continued support on the project! v3 is looking great so far.

**Comment by fabio-looker** [comment]
Thanks for the report! I've updated it in the repo.

> And thank you for the continued support on the project! v3 is looking great so far.

Thanks for the feedback! It's actually been eerily quiet since the GA v3 release, which it not a bad thing, but glad to hear some positive confirmation that everything is not on fire :)
